baseURL = 'http://ofnote.github.io/'
languageCode = 'en-us'
title = 'OffNote Labs Research Pages'
theme = 'PaperMod' #HugoTeX
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"



